export const GET_PRODUCTS_ZALANDO = 'GET_PRODUCTS_ZALANDO'
export const GET_PRODUCTS_ZALANDO_EXITO = 'GET_PRODUCTS_ZALANDO_EXITO'
export const GET_PRODUCTS_ZALANDO_ERROR = 'GET_PRODUCTS_ZALANDO_ERROR'

export const GET_PRODUCT_ZALANDO = 'GET_PRODUCT_ZALANDO'
export const GET_PRODUCT_ZALANDO_EXITO = 'GET_PRODUCT_ZALANDO_EXITO'
export const GET_PRODUCT_ZALANDO_ERROR = 'GET_PRODUCT_ZALANDO_ERROR'

export const GET_SIZE_PRODUCT_ZALANDO = 'GET_SIZE_PRODUCT_ZALANDO'
export const GET_SIZE_PRODUCT_ZALANDO_EXITO = 'GET_SIZE_PRODUCT_ZALANDO_EXITO'
export const GET_SIZE_PRODUCT_ZALANDO_ERROR = 'GET_SIZE_PRODUCT_ZALANDO_ERROR'

export const GET_ALL_SIZE = 'GET_ALL_SIZE'
export const GET_ALL_SIZE_EXITO = 'GET_ALL_SIZE_EXITO'
export const GET_ALL_SIZE_ERROR = 'GET_ALL_SIZE_ERROR'

export const GET_ALL_BRANDS = 'GET_ALL_BRANDS'
export const GET_ALL_BRANDS_EXITO = 'GET_ALL_BRANDS_EXITO'
export const GET_ALL_BRANDS_ERROR = 'GET_ALL_BRANDS_ERROR'

export const SET_SIZE_SELECTED = 'SET_SIZE_SELECTED'
export const SET_SIZE_SELECTED_EXITO = 'SET_SIZE_SELECTED_EXITO'
export const SET_SIZE_SELECTED_ERROR = 'SET_SIZE_SELECTED_ERROR'

export const GET_PRODUCT_OFFERT_ZALANDO = 'GET_PRODUCT_OFFERT_ZALANDO'
export const GET_PRODUCT_OFFERT_ZALANDO_EXITO = 'GET_PRODUCT_OFFERT_ZALANDO_EXITO'
export const GET_PRODUCT_OFFERT_ZALANDO_ERROR = 'GET_PRODUCT_OFFERT_ZALANDO_ERROR'