export const GET_PRICES_BY_PRODUCT = 'GET_PRICES_BY_PRODUCT'
export const GET_PRICES_BY_PRODUCT_EXITO = 'GET_PRICES_BY_PRODUCT_EXITO'
export const GET_PRICES_BY_PRODUCT_ERROR = 'GET_PRICES_BY_PRODUCT_ERROR'